[package]
name = "smile"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.30.0", features = ["crossterm"]}
color-eyre = "0.6"
unicode-segmentation = "1.12.0"
unicode-width = "0.2.2"
clap = { version = "4.5.56", features = ["derive"] }
